# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
# https://aws.amazon.com/blogs/compute/optimizing-serverless-development-with-samconfig/

version=0.1
[default.build.parameters]
use_container = true
parallel = true
cached = true
skip_pull_image = true

[default.package.parameters]
s3_bucket = "lex-v2-cfn-cr-artifacts-506886316466-us-east-1"
s3_prefix = "sam-artifacts/lex-v2-cfn-cr"

[default.publish.parameters]
region = "us-east-1"

[publish-account.package.parameters]
s3_bucket = "lex-v2-cfn-cr-artifacts-777566285978-us-east-1"
s3_prefix = "sam-artifacts/lex-v2-cfn-cr"

[publish-account.publish.parameters]
region = "us-east-1"

[default.deploy.parameters]
stack_name = "lex-v2-cfn-cr"
s3_bucket = "lex-v2-cfn-cr-artifacts-506886316466-us-east-1"
s3_prefix = "sam-artifacts/lex-v2-cfn-cr"
region = "us-east-1"
fail_on_empty_changeset = false
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
tags = """
  project="LexV2CfnCr" \
  version=0.3.0 \
"""
parameter_overrides = """
  LogLevel=DEBUG \
"""